export const SET_CHANNEL = 'SET_CHANNEL';
export const SET_CHANNEL_PRIVATE = 'SET_CHANNEL_PRIVATE';
export const SET_STARRED = 'SET_STARRED';
export const SET_SHOW_ONLY_STARRED = 'SET_SHOW_ONLY_STARRED';
export const SET_NEW_MESSAGES = 'SET_NEW_MESSAGES';
export const SET_CHAT_WINDOW_SCROLL_PX = 'SET_CHAT_WINDOW_SCROLL_PX';
