export const MAIN_UPDATE_FORM_INPUTS = 'MAIN_UPDATE_FORM_INPUTS';
export const SET_SNACK = 'SET_SNACK';
export const MAIN_SHOW_INTRO = 'MAIN_SHOW_INTRO';
export const MAIN_ANIMATE_MESSAGE = 'MAIN_ANIMATE_MESSAGE';
export const SET_SWIPED_SCREEN = 'SET_SWIPED_SCREEN';
